### ISSUE TITLE
S030對菜單字串的修改未反應至菜單上

### ISSUE THREAD

**Issue by kaipingli** [twoutlook/DH5Ver0414_PUBLISH#11]
NEW

![image](https://user-images.githubusercontent.com/16411841/114534925-15c75a80-9c82-11eb-9304-a35cd5da82ef.png)

OLD
![image](https://user-images.githubusercontent.com/16411841/114535276-75be0100-9c82-11eb-91a4-74d85870a065.png)

**Comment by dreamtek002** [comment]
目前菜單是預先配置的, 含權限, 如有必要可以在相對代碼調整或增刪。如果真的要做成動態, 要再寫代碼客製，目前Radzen沒有支持動態菜單。

**Comment by twoutlook** [comment]
菜單內容已改由 PROG_MST 獲得
