### ISSUE TITLE
表USER_LOG重複索引錯誤

### ISSUE THREAD

**Issue by qamartw** [twoutlook/DH5Ver0414_PUBLISH#130]
讀寫同一DB, 快速按WEB和WES兩邊的Query
<br/>
先按WEB, 再按WES
![wes error](https://user-images.githubusercontent.com/71858189/120759321-7ddd4300-c545-11eb-971d-570ffd9fc0fe.png)
<br/>
先按WES, 再按WEB
![web error](https://user-images.githubusercontent.com/71858189/120759383-8c2b5f00-c545-11eb-9177-93cfac1af7cd.png)

**Comment by twoutlook** [comment]
【0.15.53_USER_LOG】 一秒鐘之內有超過一筆的同 PK log, 直接略過不處理
